# Generated by Django 6.0.3 on 2026-03-11 11:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la categoría (ej: Alimentación, Transporte)', max_length=100, verbose_name='Nombre de la categoría')),
                ('type', models.CharField(choices=[('INCOME', 'Ingreso'), ('EXPENSE', 'Gasto')], help_text='Indica si la categoría es para ingresos o gastos', max_length=10, verbose_name='Tipo de categoría')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional de la categoría', null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la categoría está activa y disponible para uso', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('user', models.ForeignKey(help_text='Usuario propietario de la categoría', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INCOME', 'Ingreso'), ('EXPENSE', 'Gasto')], help_text='Indica si es un ingreso o un gasto', max_length=10, verbose_name='Tipo de transacción')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto de la transacción (siempre positivo)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('description', models.CharField(help_text='Descripción breve de la transacción', max_length=255, verbose_name='Descripción')),
                ('notes', models.TextField(blank=True, help_text='Notas o detalles adicionales sobre la transacción', null=True, verbose_name='Notas adicionales')),
                ('transaction_date', models.DateTimeField(help_text='Fecha y hora en que ocurrió la transacción', verbose_name='Fecha de la transacción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('category', models.ForeignKey(help_text='Categoría a la que pertenece esta transacción', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.category', verbose_name='Categoría')),
                ('user', models.ForeignKey(help_text='Usuario propietario de la transacción', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'type', 'is_active'], name='transaction_user_id_4fdd41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name', 'type')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-transaction_date'], name='transaction_user_id_64ff44_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'type'], name='transaction_user_id_4685bf_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', '-transaction_date'], name='transaction_categor_af0c2c_idx'),
        ),
    ]
